### DISCUSSION TITLE
Configuración zeronet persistente

### DISCUSSION THREAD

**Discussion by DonTomate24** [Pipepito/acestream-scraper#34] [General]
Buenas tardes,

Cada vez que se actualiza la imagen y se reconstruye el contenedor la config de zeronet se pierde y queda como una nueva instalación. Pese a tener la config asignada en un volumen persistente, la configuración de idioma, permisos de admin en página propia y conexión a listas se restablece, teniendo que conectar a todas de nuevo para que realicen conexión de nuevo. ¿Habría posibilidad de incluir la config de zeronet en un volumen persistente para que se mantenga en cada actualización de imagen?

Saludos!

**Comment by Pipepito** [comment]
Puedes darme más detalles? En mi caso el fichero de configuración sigue siendo el primero que le monté y no he tenido ninguna pega con ello.

**Comment by DonTomate24** [comment]
Por supuesto! Cuando entro a Zeronet por el puerto doy permiso de admin a mi página y cuando entro a otra, carga la primera vez los peers, quedando registrada en mi página en el menú de la izquierda como sitio conectado. Por más que reinicie el contenedor siguen conectadas esas páginas. 
Si reconstruyo el contenedor con la misma imagen, o con la nueva cuando se actualiza al entrar está "vacío" el Zeronet, tengo que volver a dar permiso de admin y reabrir las páginas para que se conecten de nuevo, ya que se desconectan. Te adjunto captura tras reconstruir. 

![Image](https://github.com/user-attachments/assets/1d636808-2482-457b-95a0-4317534859b3)

**Comment by Pipepito** [comment]
Eso es tema del directorio de datos de zeronet, si no me equivoco deberías ser capaz de montar un volumen a esa ubicación directamente si quieres que se persista, como no era mi plan en absoluto el mantener el zeronet para un uso habitual ni lo he tenido en consideración.

Igual lo siguiente va a parecer borde, no es mi intención 

No puedo estar dando soporte a funcionalidades de zeronet per se, el objetivo del repositorio y la app es hacer un scraper que puede usar enlaces de zeronet y para ello se instala dentro del docker, funciona para lo que se necesita.

Ahora bien, eso no quiere decir que no vaya a meter nice to have como estos, pero no es mi prioridad.

**Comment by DonTomate24** [comment]
Nada hombre, no es una exigencia ni mucho menos agregar funcionalidades de Zeronet. El scraper está genial, y además al llevar "en el pack" también Zeronet es mucho más cómodo que tener otro Zeronet por ahí rodando para uso principal, por eso salen estas cosillas, quizá por un uso mayor al pensado realmente en el contenedor. Le echo un ojo para montar el directorio en un volumen, gracias!

**Comment by Pipepito** [comment]
Pues si encuentras la ruta y me la pones aquí lo añadiré al readme :) 

Gracias por tu comprensión!

**Comment by Pipepito** [comment]
Ya que me he puesto con #37 estoy persisitiendo el ZeroNet/data también :D

Total, lo está haciendo Claude.

**Comment by DonTomate24** [comment]
Justo lo había hecho ahora por la mañana, con persistir la ruta /app/ZeroNet/data se mantiene todo al recrear, lo he verificado varias veces.
Te dejo el compose que utilizo ya que estoy, por si quieres incluirlo en el readme de paso para los que somos fans de usar compose:

```
services:
    acestream-scraper:
        image: pipepito/acestream-scraper
        container_name: acestream-scraper
        ports:
            - 8000:8000
            - 43110:43110
            - 43111:43111
        environment:
            - TZ=Europe/Madrid
        volumes:
            - ${PWD}/config:/app/config
            - ${PWD}/zeronet:/app/ZeroNet/data
        restart: unless-stopped
```

Yo he separado la config del scraper y de zeronet en carpetas diferentes, pero ya lo adaptas como te guste más. Saludos!
Edit: actualizo en el compose el nombre del contenedor que había dejado el que le puse yo para localizarlo mejor.
