### ISSUE TITLE
Links generated not working

### ISSUE THREAD

**Issue by hvmzx** [Pipepito/acestream-scraper#103]
I was using the scraper for a minute and it was working well, but the past few weeks i've been having this issue where none of the links generated (192.168...) work in VLC while they used to before.

Here is my compose : 

```
acestream-scraper:
    image: pipepito/acestream-scraper:latest
    container_name: acestream-scraper
    environment:
      - ENABLE_TOR=false
      - ENABLE_ACEXY=true
      - ENABLE_ACESTREAM_ENGINE=true
      - ACESTREAM_HTTP_PORT=6878
      - FLASK_PORT=8000
      - ACEXY_LISTEN_ADDR=:8080
      - ACEXY_HOST=localhost
      - ACEXY_PORT=6878
      - ALLOW_REMOTE_ACCESS=no
      - ACEXY_NO_RESPONSE_TIMEOUT=15s
      - ACEXY_BUFFER_SIZE=5MiB
      - ACESTREAM_HTTP_HOST=localhost
    ports:
      - "8000:8000"  # Flask application
      - "8080:8080"  # Acexy proxy
      - "8621:8621"  # Acestream P2P Port
      - "43110:43110"  # ZeroNet UI
      - "43111:43111"  # ZeroNet peer
      - "26552:26552"  # ZeroNet peer (and the volumes of course)
```

What could explain the acstream:// links working but not their exposition into the base_url one ?
